version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: eris
      POSTGRES_PASSWORD: REDACTED
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eris"]
      interval: 5s
      timeout: 5s
      retries: 5

  #cache layer
  redis:
    image: redis:7-alpine #lightweight
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"] #checks if Redis is responding
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
    postgres_data:
